baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Posts'
  url = '/posts/'
  weight = 2
[[menu.main]]
  name = 'About'
  url = '/about/'
  weight = 3
[[menu.main]]
  name = 'Projects'
  url = '/projects/'
  weight = 4
[[menu.main]]
  name = 'Tags'
  url = '/tags/'
  weight = 5
