baseURL = 'https://www.hsingh.dev/'
languageCode = 'en-us'
title = 'hsingh.dev'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Posts'
  url = '/posts/'
  weight = 2
[[menu.main]]
  name = 'Projects'
  url = '/projects/'
  weight = 3
