baseURL = 'https://www.hsingh.dev/'
languageCode = 'en-us'
title = 'hsingh.dev'

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 1
[[menu.main]]
  name = 'Blog'
  url = '/blog/'
  weight = 2
[[menu.main]]
  name = 'Projects'
  url = '/projects/'
  weight = 3
[[menu.main]]
  name = 'Art'
  url = '/art/'
  weight = 4
[[menu.main]]
  name = 'Tags'
  url = '/tags/'
  weight = 5
